package nightcoder.javafx;

import java.util.ArrayList;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import nightcoder.NightCoder;
import nightcoder.ui.Ui;

public class Main extends Application {
    /* `/images/DALL-E_Guest User.png` generated by DALL-E using ChatGPT */
    private Image userImage = new Image(this.getClass().getResourceAsStream("/images/DALL-E_Guest User.png"));
    /* `/images/DALL-E_NightCoder Bot.png` generated by DALL-E using ChatGPT */
    private Image botImage = new Image(this.getClass().getResourceAsStream("/images/DALL-E_NightCoder Bot.png"));
    private NightCoder nightCoder = new NightCoder();
    private ScrollPane scrollPane;
    private VBox dialogContainer;
    private TextField userInput;
    private Button sendButton;
    private Scene scene;

    @Override
    public void start(Stage stage) {
        this.scrollPane = new ScrollPane();
        this.dialogContainer = new VBox();
        this.scrollPane.setContent(this.dialogContainer);

        this.userInput = new TextField();
        this.userInput.setOnAction((event) -> {
            handleUserInput();
        });
        this.sendButton = new Button("Send");
        this.sendButton.setOnMouseClicked((event) -> {
            handleUserInput();
        });

        ArrayList<DialogBox> welcomeDialogs = new ArrayList<>();
        welcomeDialogs.add(DialogBox.ofNightCoder(Ui.getWelcomeString(1), this.botImage));
        welcomeDialogs.add(DialogBox.ofNightCoder(Ui.getWelcomeString(2), this.botImage));
        welcomeDialogs.add(DialogBox.ofNightCoder(Ui.getWelcomeString(3), this.botImage));
        welcomeDialogs.add(DialogBox.ofNightCoder(Ui.getWelcomeString(4), this.botImage));
        this.dialogContainer.getChildren().addAll(welcomeDialogs);

        AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(this.scrollPane, this.userInput, this.sendButton);

        this.scene = new Scene(mainLayout);

        stage.setScene(this.scene);
        stage.show();

        //Formatting the window to look as expected

        stage.setTitle("NightCoder");
        stage.setResizable(false);
        stage.setMinHeight(600.0);
        stage.setMaxHeight(600.0);
        stage.setMinWidth(400.0);
        stage.setMaxWidth(400.0);

        mainLayout.setPrefSize(400.0, 600.0);

        this.scrollPane.setPrefSize(385, 535);
        this.scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        this.scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.ALWAYS);

        this.scrollPane.setVvalue(1.0);
        this.scrollPane.setFitToWidth(true);

        this.dialogContainer.setPrefHeight(Region.USE_COMPUTED_SIZE);
        this.dialogContainer.heightProperty().addListener((observable) -> scrollPane.setVvalue(1.0));

        this.userInput.setPrefWidth(325.0);

        this.sendButton.setPrefWidth(55.0);

        AnchorPane.setTopAnchor(this.scrollPane, 1.0);

        AnchorPane.setBottomAnchor(this.sendButton, 1.0);
        AnchorPane.setRightAnchor(this.sendButton, 1.0);

        AnchorPane.setLeftAnchor(this.userInput, 1.0);
        AnchorPane.setBottomAnchor(this.userInput, 1.0);
    }

    private void handleUserInput() {
        String userText = this.userInput.getText();
        String nightCoderText = this.nightCoder.getResponse(userText);
        this.dialogContainer.getChildren().addAll(
                DialogBox.ofUser(userText, this.userImage),
                DialogBox.ofNightCoder(nightCoderText, this.botImage)
        );
        this.userInput.clear();
    }
}
